### ISSUE TITLE
socket.error: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by ghost** [miguelgrinberg/flasky-with-celery#6]
I've gotten this app to run but when I try to run:
`celery inspect active`
I get a:
`socket.error: [Errno 61] Connection refused`

Any ideas how I can fix this? 

Thank you

**Comment by miguelgrinberg** [comment]
Do you have a stack trace for the error?

**Comment by ghost** [comment]
`(venv) Jacobs-MacBook-Pro:flasky-with-celery jacob$ celery inspect active
Traceback (most recent call last):
  File "/Users/jacob/Documents/pythonTests/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 324, in run
    return self.do_call_method(args, **kwargs)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 346, in do_call_method
    callback=self.say_remote_command_reply)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 385, in call
    return getattr(i, method)(*args)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/app/control.py", line 81, in active
    return self._request('dump_active', safe=safe)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/app/control.py", line 307, in broadcast
    limit, callback, channel=channel,
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/kombu/pidbox.py", line 283, in _broadcast
    chan = channel or self.connection.default_channel
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/kombu/connection.py", line 757, in default_channel
    self.connection
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/kombu/connection.py", line 742, in connection
    self._connection = self._establish_connection()
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/kombu/connection.py", line 697, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 61] Connection refused`

I have included the traceback for the error above.

**Comment by miguelgrinberg** [comment]
This is Celery failing. Was the command just `celery inspect active`, or did you also have the `-A` option to point celery to your project? If that was missing, try adding the same `-A` you use for running the workers.

**Comment by ghost** [comment]
So I did the command `celery worker -A inspect active` and `celery -A inspect active` and now I get the error for both:

`Traceback (most recent call last):
  File "/Users/jacob/Documents/pythonTests/venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/Users/jacob/Documents/pythonTests/venv/lib/python2.7/site-packages/celery/app/utils.py", line 240, in find_app
    found = sym.celery
AttributeError: 'module' object has no attribute 'celery'`

**Comment by miguelgrinberg** [comment]
`-A` takes an argument. See how you run the workers, this should be the same.

**Comment by ghost** [comment]
I used this command `celery -A celery_worker.celery inspect active`
and now have the error: `Error: No nodes replied within time constraint.` printed in red.
(Redis is running)

**Comment by miguelgrinberg** [comment]
Hmm. It appears this is a Celery bug. I'm not clear if it is solved or not, people are still seeing this. See https://github.com/celery/celery/issues/1456 and https://github.com/celery/celery/issues/3453.

**Comment by ghost** [comment]
I will look at those, thank you.
